site_name: IS/IT Strategy Documentation
site_url: https://marianojgnlz.github.io/source_of_truth/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # If you have features or palette, they would be here

plugins:
  - search
  - mkdocs_quiz

docs_dir: ../unidades # Points to your 'unidad_1' directory relative to this mkdocs.yml

nav:
  - 'Unidad 1: Introducción':
    - 'Índice Unidad 1': 'unidad_1/00_indice_unidad_1.md'
    - 'Mapa Mental Interactivo': 'unidad_1/mapa_mental_interactivo.md'
    - '1. Introducción a la Administración y Estrategia': 'unidad_1/01_Introduccion_Administracion_Estrategia.md'
    - '2. El Sistema de Información en la Empresa': 'unidad_1/02_Sistema_Informacion_Empresa.md'
    - '3. IS y la Cadena de Valor': 'unidad_1/03_SI_Cadena_Valor.md'
    - '4. IS y Otros Sistemas de la Empresa': 'unidad_1/04_SI_Otros_Sistemas_Empresa.md'
    - '5. El Rol de las Tecnologías de la Información': 'unidad_1/05_Rol_Tecnologias_Informacion.md'
    - '6. Planificación de IS/IT a partir de la Estrategia Empresarial': 'unidad_1/06_Planificacion_SI_TI_Desde_Estrategia_Negocio.md'
    - '7. Grupos de Trabajo en la Planificación': 'unidad_1/07_Grupos_Trabajo_Planificacion.md'
    - '8. Fases del Plan de Alineamiento IS/IT':
      - 'Resumen': 'unidad_1/08_Fases_Plan_Alineamiento.md'
      - 'Fase I: Presentación y Compromiso': 'unidad_1/08a_Fase_I_Presentacion_Compromiso.md'
      - 'Fase II: Descripción de la Situación Actual': 'unidad_1/08b_Fase_II_Descripcion_Situacion_Actual.md'
      - 'Fase III: Elaboración del Plan': 'unidad_1/08c_Fase_III_Elaboracion_Plan.md'
      - 'Fase IV: Programación de Actividades': 'unidad_1/08d_Fase_IV_Programacion_Actividades.md'
    - '9. Valor de la Información y Inversión en IS':
      - 'Resumen': 'unidad_1/09_Valor_Informacion_Inversion_SI.md'
      - 'Costos de IS': 'unidad_1/09a_Costos_SI.md'
      - 'Beneficios de IS': 'unidad_1/09b_Beneficios_SI.md'
      - 'Tipos de Inversiones en IS': 'unidad_1/09c_Tipos_Inversiones_SI.md'
    - '10. Gestión de Recursos de IS (Área de IS)':
      - 'Resumen': 'unidad_1/10_Management_Recursos_IS.md'
      - 'Rol del Área de IS': 'unidad_1/10a_Rol_SI_Area.md'
      - 'Ubicación del Área de IS': 'unidad_1/10b_Ubicacion_SI_Area.md'
      - 'Organización del Área de IS': 'unidad_1/10c_Organizacion_SI_Area.md'
    - '11. Administración de IS': 'unidad_1/11_Administracion_SI.md'
    - '12. Integración de IS y Estrategia Empresarial':
      - 'Resumen': 'unidad_1/12_Integracion_SI_Estrategia_Empresarial.md'
      - 'Contexto de la Estrategia IS/IT': 'unidad_1/12a_Contexto_Estrategia_SI_TI.md'
      - 'Entradas Clave para la Estrategia': 'unidad_1/12b_Inputs_Clave_Estrategia.md'
      - 'Cartera de Aplicaciones': 'unidad_1/12c_Cartera_Aplicaciones.md'
      - 'Formulación de la Estrategia': 'unidad_1/12d_Estrategias_Genericas_Gestion_SI_TI.md'
      - 'Implementación de la Estrategia': 'unidad_1/12e_Proyeccion_Estrategias_Cartera.md'
      - 'Seguimiento y Control de la Estrategia': 'unidad_1/12f_Migracion_Prioridades_Cartera.md'
    - '13. Las Organizaciones según Chiavenato':
      - 'Resumen': 'unidad_1/13_Organizaciones_Chiavenato.md'
      - 'Sistemas Sociales y Abiertos': 'unidad_1/13a_Organizaciones_Sistemas_Sociales_Abiertos.md'
      - 'Enfoque de Tavistock': 'unidad_1/13b_Enfoque_Tavistock_Sistema_Sociotecnico.md'
      - 'Objetivos y Racionalidad': 'unidad_1/13c_Objetivos_Racionalidad_Organizaciones.md'
    - '14. El Modelo de Explotación de Sistemas':
      - 'Resumen': 'unidad_1/14_Modelo_Explotacion.md'
      - 'Modelo Decisional': 'unidad_1/14a_Modelo_Decisional.md'
      - 'Modelo Organizacional': 'unidad_1/14b_Modelo_Organizacional.md'
      - 'Modelo Relacional': 'unidad_1/14c_Modelo_Relacional.md'
      - 'Modelo Informacional': 'unidad_1/14d_Modelo_Informacional.md'
  - 'Unidad 2: Subsistema de provisión':
    - 'Índice Unidad 2': 'unidad_2/00_indice_unidad_2.md'
    - '1. Provisión de SI/TI': 'unidad_2/01_provision_si_ti.md'
    - '2. Proceso de obtención de software': 'unidad_2/02_proceso_obtencion_software.md'
    - '3. Proceso de adquisición de Hardware': 'unidad_2/03_proceso_adquisicion_hardware.md'
    - '4. Método de Evaluación Manual (MEM)': 'unidad_2/04_metodo_evaluacion_manual_mem.md'
    - '5. Alternativas para el pago de las adquisiciones': 'unidad_2/05_alternativas_pago_adquisiciones.md'
    - '6. Requerimiento de propuestas (RPD)': 'unidad_2/06_requerimiento_propuestas_rpd.md'
    - '7. Provisión de RRHH (Chiavenato)': 'unidad_2/07_provision_rrhh_chiavenato.md'

  - 'Unidad 3: Subsistema de Aplicación':
    - 'Índice Unidad 3': 'unidad_3/00_indice_unidad_3.md'
    - 'SI/TI: Introducción': 'unidad_3/01_subsistema_aplicacion_si_ti_intro.md'
    - 'SI/TI: Caracterización de la Carga': 'unidad_3/02_caracterizacion_carga.md'
    - 'SI/TI: Sistemas de Referencia': 'unidad_3/03_sistemas_referencia.md'
    - 'SI/TI: Evaluación del Rendimiento': 'unidad_3/04_evaluacion_rendimiento_informatico.md'
    - 'SI/TI: Magnitudes a Medir': 'unidad_3/05_magnitudes_medir.md'
    - 'SI/TI: Magnitudes que Caracterizan la Carga': 'unidad_3/06_magnitudes_caracterizan_carga.md'
    - 'SI/TI: Técnicas para Evaluar un Sistema': 'unidad_3/07_tecnicas_evaluar_sistema.md'
    - 'SI/TI: Representatividad de un Modelo de Carga': 'unidad_3/08_representatividad_modelo_carga.md'
    - 'SI/TI: Planificación de la Capacidad': 'unidad_3/09_planificacion_capacidad_prestaciones.md'
    - 'RRHH: Introducción': 'unidad_3/10_subsistema_aplicacion_rrhh_intro.md'
    - 'RRHH: Socialización Organizacional': 'unidad_3/11_socializacion_organizacional.md'
    - 'RRHH: La Empresa como Sistema de Roles': 'unidad_3/12_empresa_sistema_roles.md'
    - 'RRHH: Evaluación de Procesos de Aplicación': 'unidad_3/13_evaluacion_procesos_aplicacion_personas.md'
    - 'RRHH: Diseño de Cargos': 'unidad_3/14_diseno_cargos.md'
    - 'RRHH: Enriquecimiento de Cargos': 'unidad_3/15_enriquecimiento_cargos.md'
    - 'RRHH: Descripción y Análisis de Cargos': 'unidad_3/16_descripcion_analisis_cargos.md'
    - 'RRHH: Equipo de Trabajo': 'unidad_3/17_equipo_trabajo.md'
    - 'RRHH: Evaluación de Desempeño - Introducción y Responsabilidad': 'unidad_3/18_evaluacion_desempeno_intro_responsabilidad.md'
    - 'RRHH: Evaluación de Desempeño - Objetivos y Beneficios': 'unidad_3/19_evaluacion_desempeno_objetivos_beneficios.md'
    - 'RRHH: Evaluación de Desempeño - Métodos Tradicionales': 'unidad_3/20_evaluacion_desempeno_metodos_tradicionales.md'
    - 'RRHH: Evaluación de Desempeño - Nuevas Tendencias': 'unidad_3/21_evaluacion_desempeno_nuevas_tendencias.md'
    - 'RRHH: Gestión por Competencias': 'unidad_3/22_gestion_competencias.md'

  - 'Unidad 4: Subsistemas de Desarrollo y Mantenimiento de RRHH':
    - 'Índice Unidad 4': 'unidad_4/00_indice_unidad_4.md'
    - '1. Subsistema de Desarrollo de RRHH': 'unidad_4/01_subsistema_desarrollo_rrhh_intro.md'
    - '2. Aprendizaje': 'unidad_4/02_aprendizaje.md'
    - '3. Educación': 'unidad_4/03_educacion.md'
    - '4. Entrenamiento - Introducción': 'unidad_4/04_entrenamiento_intro.md'
    - '5. Ciclo de Entrenamiento':
      - 'Resumen': 'unidad_4/05_entrenamiento_ciclo_resumen.md'
      - 'Detección de Necesidades': 'unidad_4/05a_entrenamiento_deteccion_necesidades.md'
      - 'Programa de Entrenamiento': 'unidad_4/05b_entrenamiento_programa.md'
      - 'Ejecución del Entrenamiento': 'unidad_4/05c_entrenamiento_ejecucion.md'
      - 'Evaluación de Resultados': 'unidad_4/05d_entrenamiento_evaluacion_resultados.md'
    - '6. Desarrollo Organizacional':
      - 'Introducción': 'unidad_4/06_desarrollo_organizacional_intro.md'
      - 'Características': 'unidad_4/06a_do_caracteristicas.md'
      - 'Proceso': 'unidad_4/06b_do_proceso.md'
      - 'Técnicas de Intervención': 'unidad_4/06c_do_tecnicas_intervencion.md'
      - 'Modelos': 'unidad_4/06d_do_modelos.md'
    - '7. Subsistema de Mantenimiento de RRHH': 'unidad_4/07_subsistema_mantenimiento_rrhh_intro.md'
    - '8. Recompensas y Castigos': 'unidad_4/08_recompensas_castigos.md'
    - '9. Teoría de la Inequidad': 'unidad_4/09_teoria_inequidad.md'
    - '10. Compensación y Productividad': 'unidad_4/10_compensacion_productividad.md'
    - '11. Administración de Salarios': 'unidad_4/11_compensacion_admin_salarios.md'
    - '12. Evaluación y Clasificación de Cargos':
      - 'Introducción': 'unidad_4/12_evaluacion_clasificacion_cargos_intro.md'
      - 'Métodos de Evaluación': 'unidad_4/12a_evaluacion_cargos_metodos.md'
      - 'Comité de Evaluación': 'unidad_4/12b_evaluacion_cargos_comite.md'
      - 'Clasificación de Cargos': 'unidad_4/12c_evaluacion_cargos_clasificacion.md'
    - '13. Investigación Salarial': 'unidad_4/13_investigacion_salarial.md'
    - '14. Política Salarial': 'unidad_4/14_politica_salarial.md'
    - '15. Organización sin Cargos Definitivos': 'unidad_4/15_organizacion_sin_cargos_definitivos.md'
    - '16. Nuevos Enfoques de Remuneración': 'unidad_4/16_nuevos_enfoques_remuneracion_intro.md'
    - '17. Remuneración Variable':
      - 'Resumen': 'unidad_4/17_remuneracion_variable_resumen.md'
      - 'Incentivos': 'unidad_4/17a_remuneracion_variable_incentivos.md'
      - 'Bonos': 'unidad_4/17b_remuneracion_variable_bonos.md'
      - 'Reconocimientos y Premios': 'unidad_4/17c_remuneracion_variable_reconocimientos_premios.md'
    - '18. Planes de Beneficios Sociales': 'unidad_4/18_planes_beneficios_sociales_intro.md'
    - '19. Higiene del Trabajo': 'unidad_4/19_higiene_trabajo.md'
    - '20. Seguridad del Trabajo': 'unidad_4/20_seguridad_trabajo.md'
    - '21. Relaciones Laborales': 'unidad_4/21_relaciones_laborales_intro.md'
    - '22. Plan de Carrera': 'unidad_4/22_plan_carrera.md'
  - 'Unidad 5: Subsistema de Seguimiento':
    - 'Índice Unidad 5': 'unidad_5/00_indice_unidad_5.md'
    - '1. Introducción al Subsistema de Seguimiento': 'unidad_5/01_subsistema_seguimiento_intro.md'
    - '2. Seguimiento de SI/TI - Introducción': 'unidad_5/02_seguimiento_si_ti_intro.md'
    - '3. Rendimiento y Coste': 'unidad_5/03_rendimiento_coste.md'
    - '4. Ley de Amdahl': 'unidad_5/04_ley_amdahl.md'
    - '5. Caracterización de la Carga': 'unidad_5/05_caracterizacion_carga.md'
    - '6. Teoría de Colas': 'unidad_5/06_teoria_colas.md'
    - '7. Análisis Operacional': 'unidad_5/07_analisis_operacional.md'
    - '8. Técnicas de Evaluación de Sistemas': 'unidad_5/08_tecnicas_evaluacion.md'
    - '9. Herramientas de Medida': 'unidad_5/09_herramientas_medida.md'
    - '10. Sintonización de un Sistema': 'unidad_5/10_sintonizacion_sistema.md'
    - '11. Seguimiento de RRHH - Introducción': 'unidad_5/11_seguimiento_rrhh_intro.md'
    - '12. Proceso de Control en RRHH': 'unidad_5/12_proceso_control.md'
    - '13. Criterios y Medios de Control': 'unidad_5/13_criterios_medios_control.md'
    - '14. Auditoría de RRHH': 'unidad_5/14_auditoria_rrhh.md'
  - 'Unidad 6: Control del ambiente informático':
    - 'Índice Unidad 6': 'unidad_6/00_indice_unidad_6.md'
    - '1. Introducción al Control del Ambiente Informático': 'unidad_6/01_control_ambiente_informatico_intro.md'
    - '2. Management Responsable de IS': 'unidad_6/02_management_responsable_is.md'
    - '3. Manejo de la Seguridad de los SI': 'unidad_6/03_manejo_seguridad_si.md'
    - '4. Identificación del Riesgo': 'unidad_6/04_identificacion_riesgo.md'
    - '5. Análisis del Riesgo': 'unidad_6/05_analisis_riesgo.md'
    - '6. Manejo del Riesgo': 'unidad_6/06_manejo_riesgo.md'
    - '7. Recuperación ante el Desastre': 'unidad_6/07_recuperacion_desastre.md'
    - '8. Introducción a la Auditoría de Sistemas': 'unidad_6/08_auditoria_sistemas_intro.md'
    - '9. Aspectos Clave de la Auditoría':
      - 'Resumen': 'unidad_6/09_aspectos_clave_auditoria.md'
      - 'Control Interno Informático': 'unidad_6/09a_control_interno_informatico.md'
      - 'Etapas de la Auditoría': 'unidad_6/09b_etapas_auditoria.md'
      - 'Objetos de Auditoría': 'unidad_6/09c_objetos_auditoria.md'
      - 'Riesgo del Auditor': 'unidad_6/09d_riesgo_auditor.md'
      - 'Deontología del Auditor': 'unidad_6/09e_deontologia_auditor.md'
    - '10. Perfiles de Auditores Informáticos': 'unidad_6/10_perfiles_auditores.md'
    - '11. Tipos de Auditoría': 'unidad_6/11_tipos_auditoria.md'
    - '12. Informes de Auditoría': 'unidad_6/12_informes_auditoria.md'
    - '13. Evidencia en la Auditoría': 'unidad_6/13_evidencia_auditoria.md'
  - 'Exámenes':
    - 'Unidad 1': 'interactive_exam_1.md'
    - 'Unidad 2': 'interactive_exam_2.md'
    - 'Unidad 3': 'interactive_exam_3.md'
    - 'Unidad 4': 'interactive_exam_4.md'
    - 'Unidad 5': 'interactive_exam_5.md'
    - 'Unidad 6': 'interactive_exam_6.md'
    - 'Juegos Interactivos': 'juegos_interactivos.md'
    - 'Pasapalabra': 'pasapalabra.md'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://cdn.tailwindcss.com
